<?php

declare(strict_types=1);

namespace yiiunit\framework\db\oci\command;

use yiiunit\support\OciConnection;

/**
 * @group db
 * @group oci
 * @group command
 * @group execute-reset-sequence
 */
final class ExecuteResetSequenceTest extends \yiiunit\framework\db\command\AbstractExecuteResetSequence
{
    protected function setUp(): void
    {
        parent::setUp();

        $this->db = OciConnection::getConnection();
    }

    /**
     * @dataProvider \yiiunit\framework\db\oci\provider\CommandProvider::executeResetSequence
     */
    public function testExecuteResetSequence(
        string $tableName,
        array $insertRows,
        array $expectedIds,
        int|null $value = null
    ): void {
        $this->columnSchema = [
            'id' => 'NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY',
            'name' => 'VARCHAR(128)',
        ];

        parent::testExecuteResetSequence($tableName, $insertRows, $expectedIds, $value);
    }

    public function testExecuteResetSequenceWithTableNotSequence(): void
    {
        $this->columnSchema = [
            'id' => 'NUMBER(10) PRIMARY KEY',
            'name' => 'VARCHAR(128)',
        ];

        parent::testExecuteResetSequenceWithTableNotSequence();
    }

    public function testExecuteResetSequenceWithTablePrimaryKeyComposite(): void
    {
        $this->columnSchema = [
            'id' => 'NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL',
            'category_id' => 'NUMBER(10)',
            'name' => 'VARCHAR(128)',
            'PRIMARY KEY ([[id]], [[category_id]])',
        ];

        parent::testExecuteResetSequenceWithTablePrimaryKeyComposite();
    }
}
