build: false

version: dev-{build}

image:
  - Visual Studio 2015

clone_folder: C:\projects\yii2

environment:
  matrix:
    - php_ver: 8.1.20

cache:
  - '%APPDATA%\Composer'
  - '%LOCALAPPDATA%\Composer'
  - C:\tools\php -> .appveyor.yml
  - C:\tools\composer.phar -> .appveyor.yml

init:
  - SET PATH=C:\tools\php;%PATH%

install:
  - ps: Set-Service wuauserv -StartupType Manual
  - IF NOT EXIST C:\tools\php (choco install --yes --allow-empty-checksums php --version %php_ver% --params '/InstallDir:C:\tools\php')
  - cd C:\tools\php
  - copy php.ini-production php.ini
  - echo date.timezone="UTC" >> php.ini
  - echo memory_limit=512M >> php.ini
  - echo extension_dir=ext >> php.ini
  - echo extension=php_curl.dll >> php.ini
  - echo extension=php_fileinfo.dll >> php.ini
  - echo extension=php_gd.dll >> php.ini
  - echo extension=php_intl.dll >> php.ini
  - echo extension=php_mbstring.dll >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - echo extension=php_pdo_dblib.dll >> php.ini
  - IF NOT EXIST C:\tools\composer.phar (cd C:\tools && appveyor DownloadFile https://getcomposer.org/download/2.7.0/composer.phar)

before_test:
  - ps: Get-Service | Where-Object { $_.DisplayName -like 'SQL Server*' }

  # setup SQL Server 2008
  - ps: |
    Start-Service "MSSQL`$SQL2008R2SP2"
    Start-Service "SQLBrowser"
  - sqlcmd -S "(local)\%SQLINSTANCE%" -Q "Use [master]; CREATE DATABASE yiitest;"
  - sqlcmd -S "(local)\%SQLINSTANCE%" -h -1 -Q "set nocount on; Select @@version"
  - cd C:\projects\yii2
  - php C:\tools\composer.phar update --no-interaction --no-progress --prefer-stable --no-ansi

test_script:
  - cd C:\projects\yii2
  - vendor\bin\phpunit --exclude-group mssql
