<?php

declare(strict_types=1);

namespace yiiunit\framework\db\oci\schema;

use yiiunit\support\OciConnection;

/**
 * @group db
 * @group oci
 * @group schema
 */
final class SchemaTest extends \yiiunit\framework\db\schema\AbstractSchema
{
    protected array $columnsSchema = [
        'id' => 'NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL',
        'name' => 'VARCHAR2(128)',
    ];

    protected function setUp(): void
    {
        parent::setUp();

        $this->db = OciConnection::getConnection();
    }
}
