/**
 * This is the database schema for testing Oracle support of Yii Active Record.
 */

/* CLEANUP */

BEGIN
  FOR i IN (SELECT ut.table_name FROM USER_TABLES ut) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE "' || i.table_name || '" CASCADE CONSTRAINTS';
  END LOOP;

  FOR i IN (SELECT us.sequence_name FROM USER_SEQUENCES us) LOOP
    EXECUTE IMMEDIATE 'DROP SEQUENCE "' || i.sequence_name || '"';
  END LOOP;

  FOR i IN (SELECT uv.view_name FROM USER_VIEWS uv) LOOP
    EXECUTE IMMEDIATE 'DROP VIEW "' || i.view_name || '"';
  END LOOP;
END;

/* STATEMENTS */

CREATE TABLE "constraints"
(
    "id" INTEGER NOT NULL,
    "field1" VARCHAR2(255)
);

CREATE TABLE "profile" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "description" VARCHAR2(128) NOT NULL,
  CONSTRAINT "profile_PK" PRIMARY KEY ("id") ENABLE
);

CREATE TABLE "customer" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "email" VARCHAR2(128) NOT NULL UNIQUE,
  "name" VARCHAR2(128),
  "address" VARCHAR(4000),
  "status" INTEGER DEFAULT 0,
  "bool_status" CHAR DEFAULT 0 CHECK ("bool_status" IN (0, 1)),
  "profile_id" INTEGER,
  CONSTRAINT "customer_PK" PRIMARY KEY ("id") ENABLE
);

COMMENT ON COLUMN "customer"."email" IS 'someone@example.com';

CREATE TABLE "category" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "name" VARCHAR2(128) NOT NULL,
  CONSTRAINT "category_PK" PRIMARY KEY ("id") ENABLE
);

CREATE TABLE "item" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "name" VARCHAR2(128) NOT NULL,
  "category_id" INTEGER NOT NULL REFERENCES "category"("id") ON DELETE CASCADE,
  CONSTRAINT "item_PK" PRIMARY KEY ("id") ENABLE
);

CREATE TABLE "order" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "customer_id" INTEGER NOT NULL REFERENCES "customer"("id") ON DELETE CASCADE,
  "created_at" INTEGER NOT NULL,
  "total" DECIMAL(10,0) NOT NULL,
  CONSTRAINT "order_PK" PRIMARY KEY ("id") ENABLE
);

CREATE TABLE "order_with_null_fk" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "customer_id" INTEGER,
  "created_at" INTEGER NOT NULL,
  "total" DECIMAL(10,0) NOT NULL,
  CONSTRAINT "order_with_null_fk_PK" PRIMARY KEY ("id") ENABLE
);

CREATE TABLE "order_item" (
  "order_id" INTEGER NOT NULL references "order"("id") on DELETE CASCADE,
  "item_id" INTEGER NOT NULL references "item"("id") on DELETE CASCADE,
  "quantity" INTEGER NOT NULL,
  "subtotal" DECIMAL(10,0) NOT NULL,
  CONSTRAINT "order_item_PK" PRIMARY KEY ("order_id", "item_id") ENABLE
);

CREATE TABLE "order_item_with_null_fk" (
  "order_id" INTEGER,
  "item_id" INTEGER,
  "quantity" INTEGER NOT NULL,
  "subtotal" DECIMAL(10,0) NOT NULL
);

CREATE TABLE "composite_fk" (
  "id" INTEGER NOT NULL,
  "order_id" INTEGER NOT NULL,
  "item_id" INTEGER NOT NULL,
  CONSTRAINT "composite_fk_PK" PRIMARY KEY ("id") ENABLE,
  CONSTRAINT FK_composite_fk_order_item FOREIGN KEY ("order_id", "item_id")
    REFERENCES "order_item" ("order_id", "item_id") ON DELETE CASCADE
);

CREATE TABLE "null_values" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "var1" INTEGER NULL,
  "var2" INTEGER NULL,
  "var3" INTEGER DEFAULT NULL,
  "stringcol" VARCHAR2(32) DEFAULT NULL,
  CONSTRAINT "null_values_PK" PRIMARY KEY ("id") ENABLE
);

CREATE TABLE "negative_default_values" (
    "smallint_col" SMALLINT DEFAULT -123,
    "int_col" INTEGER DEFAULT -123,
    "bigint_col" INTEGER DEFAULT -123,
    "float_col" DOUBLE PRECISION DEFAULT -12345.6789,
    "numeric_col" DECIMAL(5,2) DEFAULT -33.22
);

CREATE TABLE "type" (
  "int_col" INTEGER NOT NULL,
  "int_col2" INTEGER DEFAULT 1,
  "tinyint_col" NUMBER(3) DEFAULT 1,
  "smallint_col" SMALLINT DEFAULT 1,
  "char_col" CHAR(100) NOT NULL,
  "char_col2" VARCHAR2(100) DEFAULT 'something',
  "char_col3" VARCHAR2(4000),
  "float_col" DOUBLE PRECISION NOT NULL,
  "float_col2" DOUBLE PRECISION DEFAULT 1.23,
  "blob_col" BLOB,
  "numeric_col" DECIMAL(5,2) DEFAULT 33.22,
  "time" TIMESTAMP DEFAULT TO_TIMESTAMP('2002-01-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss') NOT NULL,
  "bool_col" CHAR NOT NULL CHECK ("bool_col" IN (0,1)),
  "bool_col2" CHAR DEFAULT 1 CHECK("bool_col2" IN (0,1)),
  "ts_default" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "bit_col" CHAR(3) DEFAULT 130 NOT NULL
);

CREATE TABLE "bool_values" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "bool_col" CHAR CHECK ("bool_col" IN (0,1)),
  "default_true" CHAR DEFAULT 1 NOT NULL CHECK ("default_true" IN (0,1)),
  "default_false" CHAR DEFAULT 0 NOT NULL CHECK ("default_false" IN (0,1)),
  CONSTRAINT "bool_values_PK" PRIMARY KEY ("id") ENABLE
);

CREATE TABLE "animal" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "type" VARCHAR2(255) NOT NULL,
  CONSTRAINT "animal_PK" PRIMARY KEY ("id") ENABLE
);

CREATE VIEW "animal_view" AS SELECT * FROM "animal";

CREATE TABLE "default_pk" (
  "id" INTEGER DEFAULT 5 NOT NULL,
  "type" VARCHAR2(255) NOT NULL,
  CONSTRAINT "default_pk_PK" PRIMARY KEY ("id") ENABLE
);

CREATE TABLE "default_multiple_pk" (
  "id" INTEGER NOT NULL,
  "second_key_column" CHAR(10) NOT NULL,
  "type" VARCHAR2(255) NOT NULL,
  CONSTRAINT "default_multiple_pk_PK" PRIMARY KEY ("id", "second_key_column") ENABLE
);

CREATE TABLE "document" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "title" VARCHAR2(255) NOT NULL,
  "content" VARCHAR(4000),
  "version" INTEGER DEFAULT 0 NOT NULL,
  CONSTRAINT "document_PK" PRIMARY KEY ("id") ENABLE
);

CREATE TABLE "department" (
  "id" INTEGER NOT NULL,
  "title" VARCHAR2(255) NOT NULL,
  CONSTRAINT "department_PK" PRIMARY KEY ("id") ENABLE
);
CREATE SEQUENCE "department_SEQ";

CREATE TABLE "employee" (
  "id" INTEGER NOT NULL,
  "department_id" INTEGER NOT NULL,
  "first_name" VARCHAR2(255) NOT NULL,
  "last_name" VARCHAR2(255) NOT NULL,
  CONSTRAINT "employee_PK" PRIMARY KEY ("id", "department_id") ENABLE
);
CREATE SEQUENCE "employee_SEQ";

CREATE TABLE "dossier" (
  "id" INTEGER NOT NULL,
  "department_id" INTEGER NOT NULL,
  "employee_id" INTEGER NOT NULL,
  "summary" VARCHAR2(255) NOT NULL,
  CONSTRAINT "dossier_PK" PRIMARY KEY ("id", "department_id") ENABLE
);

CREATE TABLE "bit_values" (
  "id" INTEGER NOT NULL,
  "val" CHAR(1) NOT NULL,
  CONSTRAINT "bit_values_PK" PRIMARY KEY ("id") ENABLE,
  CONSTRAINT "bit_values_val" CHECK ("val" IN ('1','0'))
);

CREATE TABLE "T_constraints_1"
(
    "C_id" INTEGER NOT NULL PRIMARY KEY,
    "C_not_null" INTEGER NOT NULL,
    "C_check" VARCHAR(255) NULL CHECK ("C_check" <> ''),
    "C_unique" INTEGER NOT NULL,
    "C_default" INTEGER DEFAULT 0 NOT NULL,
    CONSTRAINT "CN_unique" UNIQUE ("C_unique")
);

CREATE TABLE "T_constraints_2"
(
    "C_id_1" INTEGER NOT NULL,
    "C_id_2" INTEGER NOT NULL,
    "C_index_1" INTEGER NULL,
    "C_index_2_1" INTEGER NULL,
    "C_index_2_2" INTEGER NULL,
    CONSTRAINT "CN_constraints_2_multi" UNIQUE ("C_index_2_1", "C_index_2_2"),
    CONSTRAINT "CN_pk" PRIMARY KEY ("C_id_1", "C_id_2")
);
CREATE INDEX "CN_constraints_2_single" ON "T_constraints_2" ("C_index_1");

CREATE TABLE "T_constraints_3"
(
    "C_id" INTEGER NOT NULL,
    "C_fk_id_1" INTEGER NOT NULL,
    "C_fk_id_2" INTEGER NOT NULL,
    CONSTRAINT "CN_constraints_3" FOREIGN KEY ("C_fk_id_1", "C_fk_id_2") REFERENCES "T_constraints_2" ("C_id_1", "C_id_2") ON DELETE CASCADE
);

CREATE TABLE "T_constraints_4"
(
    "C_id" INTEGER NOT NULL PRIMARY KEY,
    "C_col_1" INTEGER NULL,
    "C_col_2" INTEGER NOT NULL,
    CONSTRAINT "CN_constraints_4" UNIQUE ("C_col_1", "C_col_2")
);

CREATE TABLE "T_upsert"
(
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ts" INTEGER NULL,
    "email" VARCHAR(128) NOT NULL UNIQUE,
    "recovery_email" VARCHAR(128) NULL,
    "address" CLOB NULL,
    "status" NUMBER(5,0) DEFAULT 0 NOT NULL,
    "orders" INTEGER DEFAULT 0 NOT NULL,
    "profile_id" INTEGER NULL,
    CONSTRAINT "CN_T_upsert_multi" UNIQUE ("email", "recovery_email")
);

CREATE TABLE "T_upsert_1"
(
    "a" INTEGER NOT NULL PRIMARY KEY
);

CREATE TABLE "T_upsert_varbinary"
(
    "id" INTEGER NOT NULL,
    "blob_col" BLOB,
    CONSTRAINT "T_upsert_varbinary_PK" PRIMARY KEY ("id") ENABLE
);

CREATE TABLE "validator_main" (
  "id" INTEGER NOT NULL,
  "field1" VARCHAR2(255),
  CONSTRAINT "validator_main_PK" PRIMARY KEY ("id") ENABLE
);

CREATE TABLE "validator_ref" (
  "id" INTEGER NOT NULL,
  "a_field" VARCHAR2(255),
  "ref"     INTEGER,
  CONSTRAINT "validator_ref_PK" PRIMARY KEY ("id") ENABLE
);

/* TRIGGERS */

/* TRIGGERS */

INSERT INTO "animal" ("type") VALUES ('yiiunit\data\ar\Cat');
INSERT INTO "animal" ("type") VALUES ('yiiunit\data\ar\Dog');


INSERT INTO "profile" ("description") VALUES ('profile customer 1');
INSERT INTO "profile" ("description") VALUES ('profile customer 3');

INSERT INTO "customer" ("email", "name", "address", "status", "bool_status", "profile_id") VALUES ('user1@example.com', 'user1', 'address1', 1, 1, 1);
INSERT INTO "customer" ("email", "name", "address", "status", "bool_status") VALUES ('user2@example.com', 'user2', 'address2', 1, 1);
INSERT INTO "customer" ("email", "name", "address", "status", "bool_status", "profile_id") VALUES ('user3@example.com', 'user3', 'address3', 2, 0, 2);

INSERT INTO "category" ("name") VALUES ('Books');
INSERT INTO "category" ("name") VALUES ('Movies');

INSERT INTO "item" ("name", "category_id") VALUES ('Agile Web Application Development with Yii1.1 and PHP5', 1);
INSERT INTO "item" ("name", "category_id") VALUES ('Yii 1.1 Application Development Cookbook', 1);
INSERT INTO "item" ("name", "category_id") VALUES ('Ice Age', 2);
INSERT INTO "item" ("name", "category_id") VALUES ('Toy Story', 2);
INSERT INTO "item" ("name", "category_id") VALUES ('Cars', 2);

INSERT INTO "order" ("customer_id", "created_at", "total") VALUES (1, 1325282384, 110.0);
INSERT INTO "order" ("customer_id", "created_at", "total") VALUES (2, 1325334482, 33.0);
INSERT INTO "order" ("customer_id", "created_at", "total") VALUES (2, 1325502201, 40.0);

INSERT INTO "order_with_null_fk" ("customer_id", "created_at", "total") VALUES (1, 1325282384, 110.0);
INSERT INTO "order_with_null_fk" ("customer_id", "created_at", "total") VALUES (2, 1325334482, 33.0);
INSERT INTO "order_with_null_fk" ("customer_id", "created_at", "total") VALUES (2, 1325502201, 40.0);

INSERT INTO "order_item" ("order_id", "item_id", "quantity", "subtotal") VALUES (1, 1, 1, 30.0);
INSERT INTO "order_item" ("order_id", "item_id", "quantity", "subtotal") VALUES (1, 2, 2, 40.0);
INSERT INTO "order_item" ("order_id", "item_id", "quantity", "subtotal") VALUES (2, 4, 1, 10.0);
INSERT INTO "order_item" ("order_id", "item_id", "quantity", "subtotal") VALUES (2, 5, 1, 15.0);
INSERT INTO "order_item" ("order_id", "item_id", "quantity", "subtotal") VALUES (2, 3, 1, 8.0);
INSERT INTO "order_item" ("order_id", "item_id", "quantity", "subtotal") VALUES (3, 2, 1, 40.0);

INSERT INTO "order_item_with_null_fk" ("order_id", "item_id", "quantity", "subtotal") VALUES (1, 1, 1, 30.0);
INSERT INTO "order_item_with_null_fk" ("order_id", "item_id", "quantity", "subtotal") VALUES (1, 2, 2, 40.0);
INSERT INTO "order_item_with_null_fk" ("order_id", "item_id", "quantity", "subtotal") VALUES (2, 4, 1, 10.0);
INSERT INTO "order_item_with_null_fk" ("order_id", "item_id", "quantity", "subtotal") VALUES (2, 5, 1, 15.0);
INSERT INTO "order_item_with_null_fk" ("order_id", "item_id", "quantity", "subtotal") VALUES (2, 5, 1, 8.0);
INSERT INTO "order_item_with_null_fk" ("order_id", "item_id", "quantity", "subtotal") VALUES (3, 2, 1, 40.0);

INSERT INTO "document" ("title", "content", "version") VALUES ('Yii 2.0 guide', 'This is Yii 2.0 guide', 0);

INSERT INTO "department" ("id", "title") VALUES (1, 'IT');
INSERT INTO "department" ("id", "title") VALUES (2, 'accounting');

INSERT INTO "employee" ("id", "department_id", "first_name", "last_name") VALUES (1, 1, 'John', 'Doe');
INSERT INTO "employee" ("id", "department_id", "first_name", "last_name") VALUES (1, 2, 'Ann', 'Smith');
INSERT INTO "employee" ("id", "department_id", "first_name", "last_name") VALUES (2, 2, 'Will', 'Smith');

INSERT INTO "dossier" ("id", "department_id", "employee_id", "summary") VALUES (1, 1, 1, 'Excellent employee.');
INSERT INTO "dossier" ("id", "department_id", "employee_id", "summary") VALUES (2, 2, 1, 'Brilliant employee.');
INSERT INTO "dossier" ("id", "department_id", "employee_id", "summary") VALUES (3, 2, 2, 'Good employee.');

INSERT INTO "validator_main" ("id", "field1") VALUES (1, 'just a string1');
INSERT INTO "validator_main" ("id", "field1") VALUES (2, 'just a string2');
INSERT INTO "validator_main" ("id", "field1") VALUES (3, 'just a string3');
INSERT INTO "validator_main" ("id", "field1") VALUES (4, 'just a string4');
INSERT INTO "validator_ref" ("id", "a_field", "ref") VALUES (1, 'ref_to_2', 2);
INSERT INTO "validator_ref" ("id", "a_field", "ref") VALUES (2, 'ref_to_2', 2);
INSERT INTO "validator_ref" ("id", "a_field", "ref") VALUES (3, 'ref_to_3', 3);
INSERT INTO "validator_ref" ("id", "a_field", "ref") VALUES (4, 'ref_to_4', 4);
INSERT INTO "validator_ref" ("id", "a_field", "ref") VALUES (5, 'ref_to_4', 4);
INSERT INTO "validator_ref" ("id", "a_field", "ref") VALUES (6, 'ref_to_5', 5);

INSERT INTO "bit_values" ("id", "val") SELECT 1, '0' FROM SYS.DUAL UNION ALL SELECT 2, '1' FROM SYS.DUAL;
