on:
  - pull_request
  - push

name: build-sqlsrv2012

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install SQL Server 2012 Native Client
      run: |
        choco install sqlserver2012commandlineutilities -y

    - name: Install SQL Server 2012 Command Line Utilities
      run: |
        choco install sqlserver2012commandlineutilities -y

    - name: Install SQL Server 2012 Management Objects
      run: |
        choco install sqlserver2012managementobjects -y

    - name: Install SQL Server 2012 Driver for PHP
      run: |
        choco install sqlsrv2012 -y
