on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'psalm.xml'

  push:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'psalm.xml'

name: build-oracle

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: PHP ${{ matrix.php }}-oracle-${{ matrix.oracle.version }}

    env:
      EXTENSIONS: oci8, pdo, pdo_oci

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest

        php:
          - 8.1
          - 8.2
          - 8.3

        oracle:
          - version: 18
            image: gvenzl/oracle-xe:18
          - version: 21
            image: gvenzl/oracle-xe:21

    services:
      oci:
        image: ${{ matrix.oracle.image }}
        ports:
          - 1521:1521
        env:
          ORACLE_PASSWORD : oracle
        options: >-
          --name=oci
          --health-cmd healthcheck.sh
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - name: Checkout.
        uses: actions/checkout@v4

      - name: Install PHP with extensions.
        uses: shivammathur/setup-php@v2
        with:
          coverage: pcov
          extensions: ${{ env.EXTENSIONS }}
          ini-values: date.timezone='UTC'
          php-version: ${{ matrix.php }}
          tools: composer:v2, pecl

      - name: Install dependencies with composer.
        run: composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi

      - name: Run Oracle tests with PHPUnit and generate coverage.
        run: vendor/bin/phpunit --group oci --coverage-clover=coverage.xml --colors=always --verbose

      - name: Upload coverage to Codecov.
        uses: codecov/codecov-action@v4
        with:
          disable_file_fixes: true
          file: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
