on:
  - pull_request
  - push

name: build-mssql-2012

jobs:
  tests:
    name: PHP ${{ matrix.php }}-sqlite-${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - windows-latest

        php:
          - 8.1

    steps:
      - name: Checkout.
        uses: actions/checkout@v4

      - name: Set up Docker
        run: |
          docker pull dbafromthecold/sqlserver2012express:rtm
          docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=YourStrong!Password' -p 1433:1433 -d dbafromthecold/sqlserver2012express:rtm
          docker ps -a

      - name: Wait for SQL Server to start
        run: |
          sleep 60  # Espera para que SQL Server esté completamente iniciado

      - name: Install PHP with extensions.
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: date.timezone='UTC'
          coverage: pcov
          tools: composer:v2
